### ISSUE TITLE
Unable to use with SectionList

### ISSUE THREAD

**Issue by sergey-king** [mohebifar/react-native-copilot#245]
When used with react-native SectionList and called with ref to enable scrolling like:
`props.start(false, refSectionList.current);`  - getting a TypeError as below;

`
TypeError: scrollView.scrollTo is not a function. (In 'scrollView.scrollTo({
                        y: yOffsett,
                        animated: false
                      })', 'scrollView.scrollTo' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
`

React-Native SectionList Inherits ScrollView Props since it's a wrapper around <VirtualizedList>, and thus inherits its props (as well as those of <ScrollView>), so I believe this should work? @mohebifar

**Comment by sergey-king** [comment]
Looks like '.scrollTo()' method is not available on SectionList. Is there a way to add SectionList `scrollToLocation()` method support. Thanks!

**Comment by jakequade** [comment]
@sergey-king for what it's worth, you can use the `getScrollResponder()` method on a sectionlist ref as the scrollview ref for the tour. It's not ideal, but it works and exposes the methods you need.

```tsx

const Thing = ({ start }: CopilotWrappedComponentProps) => {
  const scrollRef = useRef<ScrollView | undefined>().current;

  useEffect(() => {
    if (start && scrollRef) {
      start(false, scrollRef);
    }
  }, [])

  return <SectionList
    ref={(ref) => {
      scrollRef = ref?.getScrollResponder();
    }}
    // ...
  />
}

```

**Comment by sergey-king** [comment]
Good solution! Ended up switching the library
